# -*- coding: utf-8 -*-
"""CPFandCNPJ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdPP8GIfniezZdgAhUt83g-n7wC6BpR0
"""

print("Bem-vinda à plataforma! \n")

while True:

    opção = input("Deseja continuar o cadastro com:\n1 - CPF\n2 - CNPJ\n Digte a opção desejada: ")

    if opção == "1":
        nome = input("Digite seu nome completo: ")
        cpf = int(input("Digite seu cpf: "))
        email = input("Digite seu email: ")
        senha = input("Digite uma senha: ")

        print("\nCadastro realizado com sucesso!")
        print("nome ", nome)
        print("CPF",  cpf)
        print("email ", email)
        print("senha ", senha)

    elif opção == "2":
        cnpj = input("Digite o CNPJ da empresa: ")
        razao = input("Digite a razão social: ")
        nome = input("Digite o nome do representante: ")
        email = input("Digite seu email: ")
        senha = input("Digite uma senha: ")

        print("\nCadastro realizado com sucesso!")
        print("CNPJ", cnpj)
        print("Razão", razao)
        print("Nome", nome)
        print("Email", email)
        print("Senha", senha)

    else:
        print("Opção invalida ! Por favor, digite 1 para CPF ou 2 para CNPJ")

    continue